import { writeFileSync } from "node:fs";
import { join } from "node:path";
import sharp from "sharp";
import { COLOURS, markPaths, markSvg } from "./mark";
import { WORDMARK } from "../../src/components/brandWordmarkPaths";

// Writes every copy of the mark from mark.ts:
//   src/components/brandMarkPaths.ts   the site component's paths (generated)
//   public/brand/mark*.svg, logo-*.svg the exported artwork, four colourways
//   src/app/icon.svg, apple-icon.png, favicon.ico
// npm run brand

const ROOT = join(__dirname, "..", "..");
const BRAND = join(ROOT, "public", "brand");
const APP = join(ROOT, "src", "app");

/** Line weights: heavier as the mark gets smaller, so the hairlines survive. */
const WEIGHT = { site: 3, artwork: 2, share: 1.6, icon: 4, favicon: 5 };

const WAYS = {
  "": { ink: COLOURS.ink, teal: COLOURS.teal, gold: COLOURS.gold },
  "-reverse": { ink: COLOURS.paper, teal: COLOURS.tealOnInk, gold: COLOURS.goldOnInk },
  "-black": { ink: COLOURS.ink, teal: COLOURS.ink, gold: COLOURS.ink },
  "-white": { ink: COLOURS.paper, teal: COLOURS.paper, gold: COLOURS.paper },
};

const svgBody = (svg: string) => svg.replace(/^<svg[^>]*>(<title>[^<]*<\/title>)?/, "").replace(/<\/svg>$/, "");

// 1. The site component's paths.
const set = (w: number) => JSON.stringify(markPaths(w), null, 2);
writeFileSync(
  join(ROOT, "src", "components", "brandMarkPaths.ts"),
  `// Generated by \`npm run brand\` from social/brand/mark.ts. Do not edit.\n\n` +
    `/** The mark for the site, 22 to 64 px. */\nexport const MARK = ${set(WEIGHT.site)};\n\n` +
    `/** The finer cut for large display, such as the share card. */\nexport const MARK_FINE = ${set(WEIGHT.share)};\n`,
);

// 2. Artwork. The lockups set the mark beside or above the outlined wordmark
// (brandWordmarkPaths.ts), measured in the mark's own units. Stacked keeps the Flow
// artwork's proportions; horizontal centres the capitals on the horizon, so
// the right needle points into the name.
const header = (w: number, h: number) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${r2(w)} ${r2(h)}" role="img" aria-label="Atilla Barbarossa"><title>Atilla Barbarossa</title>`;
const r2 = (n: number) => Math.round(n * 100) / 100;
/** The mark's ink, from apex to feet and needle tip to needle tip. */
const INK_BOX = { x0: 3.89, x1: 96.11, y0: 11.55, y1: 88.45 };
type Lockup = { cap: number; x: number; baseline: number; box: { x0: number; x1: number; y0: number; y1: number }; scale: number };
const LOCKUPS: Record<"horizontal" | "stacked", Lockup> = {
  horizontal: (() => {
    const cap = 20, x = INK_BOX.x1 + 12;
    return { cap, x, baseline: 58.831 + cap / 2, box: { ...INK_BOX, x1: x + (WORDMARK.width * cap) / WORDMARK.capHeight }, scale: 1 };
  })(),
  stacked: (() => {
    const cap = 5.74, w = (WORDMARK.width * cap) / WORDMARK.capHeight, x = 50 - w / 2;
    return { cap, x, baseline: 106.05, box: { x0: x, x1: x + w, y0: INK_BOX.y0, y1: 106.05 }, scale: 6 };
  })(),
};
for (const [suffix, colours] of Object.entries(WAYS)) {
  const mark = markSvg(WEIGHT.artwork, colours);
  writeFileSync(join(BRAND, `mark${suffix}.svg`), mark);
  const body = svgBody(mark);
  for (const [kind, l] of Object.entries(LOCKUPS)) {
    const k = l.cap / WORDMARK.capHeight;
    const word = `<path transform="translate(${r2(l.x)} ${r2(l.baseline)}) scale(${r2(k * 1e4) / 1e4})" d="${WORDMARK.d}" fill="${colours.ink}"/>`;
    writeFileSync(
      join(BRAND, `logo-${kind}${suffix}.svg`),
      `${header((l.box.x1 - l.box.x0) * l.scale, (l.box.y1 - l.box.y0) * l.scale)}` +
        `<g transform="scale(${l.scale}) translate(${r2(-l.box.x0)} ${r2(-l.box.y0)})">${body}${word}</g></svg>`,
    );
  }
}

// 3. App icons: the colour mark on a paper tile.
const tile = (weight: number, rx: number, pad: number) => markSvg(weight, WAYS[""], { tile: { fill: COLOURS.paper, rx, pad } });

/** An .ico holding PNG images (supported by every current browser). */
function ico(pngs: Array<{ size: number; data: Buffer }>) {
  const head = Buffer.alloc(6 + 16 * pngs.length);
  head.writeUInt16LE(1, 2);
  head.writeUInt16LE(pngs.length, 4);
  let offset = head.length;
  pngs.forEach(({ size, data }, i) => {
    const e = 6 + 16 * i;
    head.writeUInt8(size % 256, e);
    head.writeUInt8(size % 256, e + 1);
    head.writeUInt16LE(1, e + 4);
    head.writeUInt16LE(32, e + 6);
    head.writeUInt32LE(data.length, e + 8);
    head.writeUInt32LE(offset, e + 12);
    offset += data.length;
  });
  return Buffer.concat([head, ...pngs.map((p) => p.data)]);
}

async function main() {
  writeFileSync(join(APP, "icon.svg"), tile(WEIGHT.icon, 18, 2));
  // iOS rounds the corners itself.
  await sharp(Buffer.from(tile(WEIGHT.icon, 0, 6)), { density: 300 }).resize(180, 180).png().toFile(join(APP, "apple-icon.png"));
  const sizes = [16, 32, 48];
  const pngs = await Promise.all(
    sizes.map(async (size) => ({
      size,
      data: await sharp(Buffer.from(tile(WEIGHT.favicon, 18, 0)), { density: 300 }).resize(size, size).png().toBuffer(),
    })),
  );
  writeFileSync(join(APP, "favicon.ico"), ico(pngs));
  console.log("brand written");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
